/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * For.java
 *
 * Created on 2011-05-26, 01:01:36
 */
package javablock.flowchart.generator;

import config.Global;
import config.translator;
import javablock.flowchart.Flowchart;
import javablock.flowchart.JBlock;
import javablock.flowchart.blocks.*;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class For extends javax.swing.JPanel implements Generator{

    /** Creates new form For */
    public For() {
        initComponents();
    }
    void reset(){
        variable.setText("i");
        initial.setText("0");
        end.setText("10");
        comp.setSelectedIndex(0);
        iterType.setSelectedIndex(0);
        iterNum.setText("1");

        declare.setSelected(true);
    }
    @Override
    public JBlock[] get(Flowchart f){
        For g=this;
        int res=JOptionPane.showConfirmDialog(Global.Window, g,"For Loop",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(res==JOptionPane.OK_OPTION){
            int p=0;
            
                JBlock[] list=new JBlock[8];
                CPUBlock init=(CPUBlock) JBlock.make(JBlock.Type.CPU, f);
                init.setCode(g.variable.getText()+" = "+g.initial.getText());
                init.setPos(0,-90);
                list[p++]=init;
                
                DecisionBlock condition=(DecisionBlock) JBlock.make(JBlock.Type.DECISION, f);
                condition.setCode(g.variable.getText()+" "+g.comp.getSelectedItem()+" "+
                        g.end.getText());
                list[p++]=condition;
                
                CPUBlock iter=(CPUBlock) JBlock.make(JBlock.Type.CPU, f);
                iter.setCode(g.variable.getText()+" "+g.iterType.getSelectedItem()
                        +"= "+g.iterNum.getText());
                iter.setPos(100,100);
                list[p++]=iter;
                
                JumpBlock jump, jump2;
                
                jump=(JumpBlock) JBlock.make(JBlock.Type.JUMP, f);
                jump.setPos(0, -50);
                init.connectTo(jump);
                jump.connectTo(condition);
                list[p++]=jump;
                
                jump2=(JumpBlock) JBlock.make(JBlock.Type.JUMP, f);
                jump2.setPos(100,0);
                condition.connectTo(jump2);
                jump2.connectTo(iter);
                list[p++]=jump2;
                
                jump2=(JumpBlock) JBlock.make(JBlock.Type.JUMP, f);
                jump2.setPos(200,-50);
                jump2.connectTo(jump);
                list[p++]=jump2;
                
                jump=(JumpBlock) JBlock.make(JBlock.Type.JUMP, f);
                jump.setPos(200, 100);
                jump.connectTo(jump2);
                iter.connectTo(jump);
                list[p++]=jump;
                
                jump=(JumpBlock) JBlock.make(JBlock.Type.JUMP, f);
                jump.setPos(0,100);
                condition.connectTo(jump);
                list[p++]=jump;
                
                return list;
            
            
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        variable = new javax.swing.JTextField();
        initial = new javax.swing.JTextField();
        end = new javax.swing.JTextField();
        comp = new javax.swing.JComboBox();
        iterNum = new javax.swing.JTextField();
        iterType = new javax.swing.JComboBox();
        declare = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("config/lang/lang"); // NOI18N
        jLabel1.setText(bundle.getString("generator.for.variable")); // NOI18N

        jLabel2.setText(bundle.getString("generator.for.initValue")); // NOI18N

        jLabel4.setText(bundle.getString("generator.for.comparsion")); // NOI18N

        jLabel5.setText(bundle.getString("generator.for.iteration")); // NOI18N

        variable.setText("i");

        initial.setText("0");

        end.setText("10");

        comp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<", "≤", "=", "≥", ">", "≠" }));

        iterNum.setText("1");

        iterType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "/" }));

        declare.setSelected(true);
        declare.setText(bundle.getString("generator.for.declare")); // NOI18N
        declare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declareActionPerformed(evt);
            }
        });

        jLabel3.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(declare)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(end, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(iterNum, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(variable, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(initial, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(initial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(iterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iterNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(declare)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void declareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_declareActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comp;
    private javax.swing.JCheckBox declare;
    private javax.swing.JTextField end;
    private javax.swing.JTextField initial;
    private javax.swing.JTextField iterNum;
    private javax.swing.JComboBox iterType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField variable;
    // End of variables declaration//GEN-END:variables
}
