package flow.gui;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JPanel;
/**
 *
 * @author Mpumpu
 */
public class MainDisplay extends javax.swing.JFrame 
{

    /**
     * Creates new form MainDisplay
     */
    public MainDisplay()  {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY.darker());
        jPanel2.setBackground(Color.white);  
        Tab();
        
        try {
                this.setIconImage(ImageIO.read(getClass().getResource("icons/icon.png")));
            } catch (Exception ex) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        newFile = new javax.swing.JButton();
        open = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        undo = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        run = new javax.swing.JButton();
        step = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        componentsInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        processingComponent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        decisionComponent = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ioComponent = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        moduleComponent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        returnComponent = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        bin = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        consoleInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        openMenuItem = new javax.swing.JMenuItem();
        renameMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        deleteMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        componentsMenuItem = new javax.swing.JMenuItem();
        consoleMenuItem = new javax.swing.JMenuItem();
        gridMenuItem = new javax.swing.JMenuItem();
        navigationMenuItem = new javax.swing.JMenuItem();
        fullScreenMenuItem = new javax.swing.JCheckBoxMenuItem();
        optionMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flow");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        newFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/24/rsz_actions-document-new-icon.png"))); // NOI18N
        newFile.setToolTipText("New");
        newFile.setActionCommand("New");
        newFile.setFocusable(false);
        newFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileActionPerformed(evt);
            }
        });
        jToolBar1.add(newFile);

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/24/rsz_open-folder-icon.png"))); // NOI18N
        open.setToolTipText("Open");
        open.setFocusable(false);
        open.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        open.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jToolBar1.add(open);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/24/rsz_actions-document-save-icon.png"))); // NOI18N
        save.setToolTipText("Save");
        save.setFocusable(false);
        save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(save);
        jToolBar1.add(jSeparator6);

        undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/24/rsz_arrows-undo-icon.png"))); // NOI18N
        undo.setToolTipText("Undo");
        undo.setEnabled(false);
        undo.setFocusable(false);
        undo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(undo);

        redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/24/rsz_arrows-redo-icon.png"))); // NOI18N
        redo.setToolTipText("Redo");
        redo.setEnabled(false);
        redo.setFocusable(false);
        redo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        redo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(redo);
        jToolBar1.add(jSeparator8);

        run.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flow/gui/icons/rsz_play-icon.png"))); // NOI18N
        run.setToolTipText("Run");
        run.setFocusable(false);
        run.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        run.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(run);

        step.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flow/gui/icons/rsz_step-forward-pressed-icon.png"))); // NOI18N
        step.setToolTipText("Step");
        step.setEnabled(false);
        step.setFocusable(false);
        step.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        step.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(step);

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flow/gui/icons/rsz_stop-icon.png"))); // NOI18N
        stop.setToolTipText("Stop");
        stop.setEnabled(false);
        stop.setFocusable(false);
        stop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(stop);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.add(jSeparator1);

        jSpinner1.setMaximumSize(new java.awt.Dimension(63, 30));
        jSpinner1.setPreferredSize(new java.awt.Dimension(63, 30));
        jToolBar1.add(jSpinner1);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("run speed");
        jToolBar1.add(jLabel1);

        componentsInternalFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Components"));
        componentsInternalFrame.setClosable(true);
        componentsInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        componentsInternalFrame.setIconifiable(true);
        componentsInternalFrame.setAutoscrolls(true);
        componentsInternalFrame.setFocusCycleRoot(false);
        componentsInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/flow/gui/icons/jframeicon.png"))); // NOI18N
        componentsInternalFrame.setPreferredSize(new java.awt.Dimension(297, 150));
        componentsInternalFrame.setRequestFocusEnabled(false);
        try {
            componentsInternalFrame.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        componentsInternalFrame.setVerifyInputWhenFocusTarget(false);
        componentsInternalFrame.setVisible(true);

        processingComponent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/tempcomponents/32/processing.png"))); // NOI18N
        processingComponent.setBorder(null);
        processingComponent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        processingComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processingComponentActionPerformed(evt);
            }
        });

        jLabel3.setText("Processing Block");

        decisionComponent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/tempcomponents/32/decision.png"))); // NOI18N
        decisionComponent.setBorder(null);
        decisionComponent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("Decision Block");

        ioComponent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/tempcomponents/32/io.png"))); // NOI18N
        ioComponent.setToolTipText("");
        ioComponent.setBorder(null);
        ioComponent.setBorderPainted(false);
        ioComponent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Input/Output Block");

        moduleComponent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/tempcomponents/32/processing.png"))); // NOI18N
        moduleComponent.setBorder(null);
        moduleComponent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setText("Module");

        returnComponent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/tempcomponents/32/return.png"))); // NOI18N
        returnComponent.setBorder(null);
        returnComponent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setText("End Block");

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(decisionComponent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(processingComponent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(ioComponent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(moduleComponent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(returnComponent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(processingComponent)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decisionComponent)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)))
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ioComponent))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)))
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moduleComponent))
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)))
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnComponent)))
                .addContainerGap())
        );
        jDesktopPane3.setLayer(processingComponent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        processingComponent.getAccessibleContext().setAccessibleName("processingComponent");
        jDesktopPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(decisionComponent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(ioComponent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ioComponent.getAccessibleContext().setAccessibleName("io");
        jDesktopPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(moduleComponent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(returnComponent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        returnComponent.getAccessibleContext().setAccessibleName("returnComponent");
        jDesktopPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane4.setViewportView(jDesktopPane3);

        javax.swing.GroupLayout componentsInternalFrameLayout = new javax.swing.GroupLayout(componentsInternalFrame.getContentPane());
        componentsInternalFrame.getContentPane().setLayout(componentsInternalFrameLayout);
        componentsInternalFrameLayout.setHorizontalGroup(
            componentsInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );
        componentsInternalFrameLayout.setVerticalGroup(
            componentsInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        bin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/48/rsz_bin-empty-icon.png"))); // NOI18N
        bin.setBorderPainted(false);
        bin.setFocusable(false);
        bin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(bin);

        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setMaximumSize(new java.awt.Dimension(80, 31));
        jSlider1.setPreferredSize(new java.awt.Dimension(50, 31));
        jToolBar2.add(jSlider1);

        jLabel2.setText("Zoom");
        jToolBar2.add(jLabel2);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(jDesktopPane2);

        jTabbedPane1.addTab("Tab1", jScrollPane5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        consoleInternalFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        consoleInternalFrame.setClosable(true);
        consoleInternalFrame.setIconifiable(true);
        consoleInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/flow/gui/icons/jframeicon.png"))); // NOI18N
        consoleInternalFrame.setVisible(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("=A Flowchart Planning and Simulation Tool=\n      Proudly brought to you by ThinkTech!");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout consoleInternalFrameLayout = new javax.swing.GroupLayout(consoleInternalFrame.getContentPane());
        consoleInternalFrame.getContentPane().setLayout(consoleInternalFrameLayout);
        consoleInternalFrameLayout.setHorizontalGroup(
            consoleInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        consoleInternalFrameLayout.setVerticalGroup(
            consoleInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consoleInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jTree1);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consoleInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(componentsInternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(componentsInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(consoleInternalFrame)
                    .addContainerGap(54, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(componentsInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(consoleInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        newFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFileMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_actions-document-new-icon.png"))); // NOI18N
        newFileMenuItem.setText("New");
        newFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newFileMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_actions-document-save-icon.png"))); // NOI18N
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveAsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_document-saveas-black.png"))); // NOI18N
        saveAsMenuItem.setText("Save As");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);
        fileMenu.add(jSeparator4);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_open-folder-icon.png"))); // NOI18N
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        renameMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rename.png"))); // NOI18N
        renameMenuItem.setText("Rename");
        fileMenu.add(renameMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/exit.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        MenuBar.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_arrows-undo-icon.png"))); // NOI18N
        undoMenuItem.setText("Undo");
        editMenu.add(undoMenuItem);

        redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        redoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_arrows-redo-icon.png"))); // NOI18N
        redoMenuItem.setText("Redo");
        redoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(redoMenuItem);
        editMenu.add(jSeparator2);

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_actions-edit-cut-icon.png"))); // NOI18N
        cutMenuItem.setText("Cut");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_copy-icon.png"))); // NOI18N
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_actions-edit-paste-icon.png"))); // NOI18N
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);
        editMenu.add(jSeparator3);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        deleteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flowicons/gui/icons/16/rsz_bin-empty-icon.png"))); // NOI18N
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        MenuBar.add(editMenu);

        viewMenu.setText("View");
        viewMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        componentsMenuItem.setText("Components");
        componentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                componentsMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(componentsMenuItem);

        consoleMenuItem.setText("Output");
        consoleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(consoleMenuItem);

        gridMenuItem.setText("Grid");
        viewMenu.add(gridMenuItem);

        navigationMenuItem.setText("Navigation");
        navigationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigationMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(navigationMenuItem);

        fullScreenMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        fullScreenMenuItem.setText("Full Screen");
        fullScreenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullScreenMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(fullScreenMenuItem);

        MenuBar.add(viewMenu);

        optionMenu.setText("Options");
        optionMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBar.add(optionMenu);

        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem2.setText("Help Contents");
        helpMenu.add(jMenuItem2);

        jMenuItem3.setText("About");
        helpMenu.add(jMenuItem3);

        MenuBar.add(helpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1363, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void redoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redoMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void newFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openActionPerformed

    
    private void componentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_componentsMenuItemActionPerformed
        // TODO add your handling code here:
        if(componentsInternalFrame.isVisible())
           componentsInternalFrame.setVisible(false);
       else
           componentsInternalFrame.setVisible(true);
    }//GEN-LAST:event_componentsMenuItemActionPerformed

    private void fullScreenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullScreenMenuItemActionPerformed
        // TODO add your handling code here:
        displayFullScreeen();
    }//GEN-LAST:event_fullScreenMenuItemActionPerformed

    private void consoleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleMenuItemActionPerformed
        // TODO add your handling code here:
       if(consoleInternalFrame.isVisible())
           consoleInternalFrame.setVisible(false);
       else
           consoleInternalFrame.setVisible(true);
    }//GEN-LAST:event_consoleMenuItemActionPerformed

    private void processingComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processingComponentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processingComponentActionPerformed

    private void navigationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigationMenuItemActionPerformed
        // TODO add your handling code here:
        if(jScrollPane2.isVisible())
           jScrollPane2.setVisible(false);
       else
           jScrollPane2.setVisible(true);
    }//GEN-LAST:event_navigationMenuItemActionPerformed

    public void displayFullScreeen()
    {        
        if(fullscreen == true)
            fullscreen = false;        
        else
            fullscreen = true;
        
        if(fullscreen)
        {
            windowSize=this.getBounds();
            this.setVisible(false);
            this.dispose();
            this.setUndecorated(true);
            Toolkit tk = Toolkit.getDefaultToolkit();
            this.setBounds(0,0,tk.getScreenSize().width, tk.getScreenSize().height);
            jToolBar1.setVisible(false);
            componentsInternalFrame.setVisible(false);
            consoleInternalFrame.setVisible(false);
            jScrollPane2.setVisible(false);
            this.setVisible(true);
        }
        else
        {
            this.setVisible(false);
            this.dispose();
            this.setUndecorated(false);
            setBounds(windowSize);
            jToolBar1.setVisible(true);
            componentsInternalFrame.setVisible(true);
            consoleInternalFrame.setVisible(true);
            jScrollPane2.setVisible(true);       
            this.setVisible(true);
        }
    }
    boolean fullscreen=false;
    Rectangle windowSize;
   
    public void Tab()
    {
        //jTabbedPane1.addTab ("Start", null);
        FlowLayout f = new FlowLayout (FlowLayout.CENTER, 5, 0);

        // Make a small JPanel with the layout and make it non-opaque
        final JPanel panelTab = new JPanel (f);
        panelTab.setOpaque (false);
        
        // Create a JButton for adding the tabs
        JButton addTabButton = new JButton ("+");
        addTabButton.setOpaque (false); 
        addTabButton.setBorder (null);
        addTabButton.setContentAreaFilled (false);
        addTabButton.setFocusPainted (false);
        addTabButton.setFocusable (true);
        
        //Add the button to the panel
        panelTab.add (addTabButton);

        jTabbedPane1.setTabComponentAt (jTabbedPane1.getTabCount ()-1, panelTab);

        ActionListener listener = new ActionListener () {
            @Override
            public void actionPerformed (ActionEvent e) {
                String title = "Tab " + String.valueOf (jTabbedPane1.getTabCount()+1);
                jTabbedPane1.addTab (title, null);
                jTabbedPane1.setTabComponentAt (jTabbedPane1.getTabCount ()-1, panelTab);
            }
        };
        addTabButton.setFocusable (true);
        addTabButton.addActionListener (listener);
    }
    
public static boolean showSplash=true;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton bin;
    private javax.swing.JInternalFrame componentsInternalFrame;
    private javax.swing.JMenuItem componentsMenuItem;
    private javax.swing.JInternalFrame consoleInternalFrame;
    private javax.swing.JMenuItem consoleMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JButton decisionComponent;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem fullScreenMenuItem;
    private javax.swing.JMenuItem gridMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton ioComponent;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton moduleComponent;
    private javax.swing.JMenuItem navigationMenuItem;
    private javax.swing.JButton newFile;
    private javax.swing.JMenuItem newFileMenuItem;
    private javax.swing.JButton open;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JButton processingComponent;
    private javax.swing.JButton redo;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JMenuItem renameMenuItem;
    private javax.swing.JButton returnComponent;
    private javax.swing.JButton run;
    private javax.swing.JButton save;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton step;
    private javax.swing.JButton stop;
    private javax.swing.JButton undo;
    private javax.swing.JMenuItem undoMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}

